Test cases for Package_Item(Model)
aviacommerce/avia pull request #443
Opened 2019-01-23 09:01 UTC by Jeshan7

## Why?
    - Coverage of package_item tests was low 

## This change addresses the need by:
   - Updated the test cases in test/data/model/package_item_test.exs
   - Wrote new test cases in test/data/model/package_item_test.exs

[delivers #163248592]

## Checklist

- [ ] I have read [CONTRIBUTING.md][contributing].
- [ ] My code follows the [style guidelines][contributing] of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code does not generate any (new) [`credo`][credo] and compile-time warnings.
- [ ] I have updated the documentation wherever necessary.
- [ ] I have added tests to cover my changes.

[contributing]: https://github.com/aviabird/snitch/CONTRIBUTING.md
[credo]: https://github.com/rrrene/credo

2019-01-23 11:12 UTC, arjun289 requested changes

2019-01-23 11:12 UTC, arjun289 commented on apps/snitch_core/test/data/model/package_item_test.exs
> +      assert {:ok, _} =
The approach here is not correct.

You only have to create an empty package, then use the line_item you have set up to create a package item. You are already creating a package_item in `new_package` and using the attributes of that to create another package_item.

2019-01-23 11:12 UTC, arjun289 commented on apps/snitch_core/test/data/model/package_item_test.exs
> +  defp new_package(context) do
Break the function into two one should create a `package` another should create `package_item` and you should pass params which are required explicitly. You can make use of the context. The way `embedded_shipping_methods` is passed.

2019-01-23 11:12 UTC, arjun289 commented on apps/snitch_core/test/data/model/package_item_test.exs
> +      map = %{quantity: package_item.quantity, delta: package_item.delta}
Use something which is unique for `package item` for e.g. package number. The keys that you have used are not unique for a package item. You have used quantity and delta do you think these are unique for `package items`

2019-01-23 11:12 UTC, SagarKarwande requested changes

2019-01-23 11:12 UTC, SagarKarwande commented on apps/snitch_core/test/data/model/package_item_test.exs
> +    test "with invalid attributes" do
Test statement is incorrect

2019-01-23 11:12 UTC, SagarKarwande commented on apps/snitch_core/test/data/model/package_item_test.exs
> +    test "with invalid params", context do
Test statement is incorrect

2019-01-24 06:02 UTC, arjun289 approved these changes
Looks good now.

2019-01-24 06:10 UTC, SagarKarwande approved these changes

2019-01-24 06:14 UTC, merged